name: SipX Windows build
on: push

env:
  CFLAGS: "-O0 -g -fPIC -fpermissive"
  MAKE_USE_CPUS: " -j 1 "

jobs:
  # Label of the runner job
  sipx-build-windows:

    runs-on: windows-2019
    
    steps:
    
      - name: check env
        run: |
          $Env:Path
          $Env:Path = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools; $Env:Path"
          $env:Path
          echo $SHELL
          python3 --version
          VsMSBuildCmd.bat -arch=x64 -winsdk=10.0.19041.0
