name: SipX Linux build
on: push

env:
  CFLAGS: "-O0 -g -fPIC -fpermissive"

jobs:
  # Label of the runner job
  sipx-build-linux:
    # You must use a Linux environment when using service containers or container jobs
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    
    steps:
    
      - name: install dev and runtime packages
        run: sudo apt-get install git g++ subversion gdb make libpcre3-dev autoconf automake libtool pkg-config valgrind libasound2-dev alsa-utils libssl-dev patch libspeex-dev libspandsp-dev bc
        
      - name: checkout ${{ github.ref }}
      # Downloads a copy of the code in your repository before running CI tests
        uses: actions/checkout@v3
        with:
          repository: sipXtapi/sipXtapi
          
      - name: view checkout results
        run: |
          ls -l
          
      - name: build portlib
        run: |
          echo CFLAGS: $CFLAGS
          cd sipXportLib
          if [ ! -f configure ] ; then autoreconf -if ; fi
          patch configure < ../configure.patch
          if [ ! -f Makefile ] ; then ./configure --without-openssl --without-cppunit; fi
          make
          make tests
          
      - name: build sdplib
        run: |
          echo PWD: `pwd`
          echo CFLAGS: $CFLAGS
          cd sipXsdpLib
          if [ ! -f configure ] ; then autoreconf -if ; fi
          patch configure < ../configure.patch
          if [ ! -f Makefile ] ; then ./configure --without-openssl --without-cppunit; fi
          make
          make tests
